# %YAML:1.1 # need to specify the file type at the top!


system:
  use_data_source: 1
  # start_idx: 25
  # end_idx: 40
  start_idx: 0
  end_idx: 63
  maximum_depth_for_depthimage: 100
  minimum_depth_for_depthimage: 0.001
  maximum_z_for_pointcloud: 100 # lidar reliable distance is 100 meter maximum
  minimum_z_for_pointcloud: 0.001
  isFilterDepthByKNN: false
  K_for_filterdepth: 1

output:
  isOutput: true
  path: /mnt/lboro_nas/personal/Zhipeng/wai_data/ETH3d_forest_64
  isSaveVisualizationDepthImage: true
  maximum_depth_for_vis_depthimage: -1
  minimum_depth_for_vis_depthimage: -1


visualization:
  isVisualization: false


# images_rig_cam7 -> CAMERA_ID 0
# images_rig_cam6 -> CAMERA_ID 1
# images_rig_cam5 -> CAMERA_ID 2
# images_rig_cam4 -> CAMERA_ID 3


cameras:
  camera0:
    id: 3
    name: images_rig_cam4_undistorted
    imagepath: /mnt/lboro_nas/personal/Zhipeng/eth3d/multi_view_training_rig/forest/images/images_rig_cam4
    camera_model: pinhole
    original_resolution: [752, 480]
    original_intrinsics: [543.476, 542.696, 410.518, 226.622] #fx, fy, cu, cv
    distortion_model: thin_prism_fisheye
    distortion_coeffs: [-0.0696259, -0.0619737, 0.00136507, -0.00207556, 0.097466, -0.063834, 0.00976896, -0.00190205] #k1,k2,p1,p2,k3,k4,sx1,sy1
    resolution: [752, 480] # width x height, don't larger than original resolution

  camera1:
    id: 2
    name: images_rig_cam5_undistorted
    imagepath: /mnt/lboro_nas/personal/Zhipeng/eth3d/multi_view_training_rig/forest/images/images_rig_cam5
    camera_model: pinhole
    original_resolution: [752, 480]
    original_intrinsics: [539.39, 539.777, 353.777, 227.355] #fx, fy, cu, cv
    distortion_model: thin_prism_fisheye
    distortion_coeffs: [-0.0695354, -0.0487684, -0.00550784, -0.00798835, 0.0623511, -0.0362409, 0.0466469, 0.0250837] #k1,k2,p1,p2,k3,k4,sx1,sy1
    resolution: [752, 480] # width x height, don't larger than original resolution

# GT depth
sensor3ds:
  sensor3d0:
    id: 0
    sensor3dtype: imagedepth
    camera_id: 3
    name: gt_depth_in_cam4_plane
    sensor3dpath: /mnt/lboro_nas/personal/Zhipeng/eth3d/multi_view_training_rig_depth/forest_rig_depth/forest/ground_truth_depth/images_rig_cam4
    camera_model: pinhole
    original_resolution: [752, 480]
    original_intrinsics: [543.476, 542.696, 410.518, 226.622] #fx, fy, cu, cv
    distortion_model: thin_prism_fisheye
    distortion_coeffs: [-0.0696259, -0.0619737, 0.00136507, -0.00207556, 0.097466, -0.063834, 0.00976896, -0.00190205] #k1,k2,p1,p2,k3,k4,sx1,sy1
    xyz_scale_factor: [1.0, 1.0, 1.0]
    down_sample_rate: 1.0

  sensor3d1:
    id: 1
    sensor3dtype: imagedepth
    camera_id: 3
    name: gt_depth_in_cam4_plane_downsampled_40_percent
    sensor3dpath: /mnt/lboro_nas/personal/Zhipeng/eth3d/multi_view_training_rig_depth/forest_rig_depth/forest/ground_truth_depth/images_rig_cam4
    camera_model: pinhole
    original_resolution: [752, 480]
    original_intrinsics: [543.476, 542.696, 410.518, 226.622] #fx, fy, cu, cv
    distortion_model: thin_prism_fisheye
    distortion_coeffs: [-0.0696259, -0.0619737, 0.00136507, -0.00207556, 0.097466, -0.063834, 0.00976896, -0.00190205] #k1,k2,p1,p2,k3,k4,sx1,sy1
    xyz_scale_factor: [1.0, 1.0, 1.0]
    down_sample_rate: 0.4

  sensor3d2:
    id: 2
    sensor3dtype: imagedepth
    camera_id: 2
    name: gt_depth_in_cam5_plane
    sensor3dpath: /mnt/lboro_nas/personal/Zhipeng/eth3d/multi_view_training_rig_depth/forest_rig_depth/forest/ground_truth_depth/images_rig_cam5
    camera_model: pinhole
    original_resolution: [752, 480]
    original_intrinsics: [539.39, 539.777, 353.777, 227.355] #fx, fy, cu, cv
    distortion_model: thin_prism_fisheye
    distortion_coeffs: [-0.0695354, -0.0487684, -0.00550784, -0.00798835, 0.0623511, -0.0362409, 0.0466469, 0.0250837] #k1,k2,p1,p2,k3,k4,sx1,sy1
    xyz_scale_factor: [1.0, 1.0, 1.0]
    down_sample_rate: 1.0

  sensor3d3:
    id: 3
    sensor3dtype: imagedepth
    camera_id: 2
    name: gt_depth_in_cam5_plane_downsampled_40_percent
    sensor3dpath: /mnt/lboro_nas/personal/Zhipeng/eth3d/multi_view_training_rig_depth/forest_rig_depth/forest/ground_truth_depth/images_rig_cam5
    camera_model: pinhole
    original_resolution: [752, 480]
    original_intrinsics: [539.39, 539.777, 353.777, 227.355] #fx, fy, cu, cv
    distortion_model: thin_prism_fisheye
    distortion_coeffs: [-0.0695354, -0.0487684, -0.00550784, -0.00798835, 0.0623511, -0.0362409, 0.0466469, 0.0250837] #k1,k2,p1,p2,k3,k4,sx1,sy1
    xyz_scale_factor: [1.0, 1.0, 1.0]
    down_sample_rate: 0.4


data_source1:
  trajectoryname: eth3d
  trajectorytype: poses_for_all_cameras
  trajectory_path: /mnt/lboro_nas/personal/Zhipeng/eth3d/multi_view_training_rig/forest/rig_calibration/images.txt
  used_sensor3d_idxes: [1]
  num_cumulation: [0, 0] # if there are two used sensor3ds, you need to specify two numbers of cumulation.
  used_camera_idxes: [0]





